### ISSUE TITLE
Feedback: "Navigate to the last breadcrumb link" (Breadcrumb Example, Test 6)

### ISSUE THREAD

**Issue by jha11y** [w3c/aria-at#811] opened 2022-08-27 13:05 UTC
## Description of Behavior

I am unsure if the assertions are correct.  If a user is using Ctrl + Option + Left, that is reverse navigation.  The assertions seem to indicate that this is forward navigation as the don't mention boundaries.  Other backward navigation tests have assertions that include boundary indication.

## Test Setup

- Test File: [test-06-navigate-to-the-last-breadcrumb-link-interaction-voiceover_macos.collected.html](https://aria-at.netlify.app/tests/breadcrumb/test-06-navigate-to-the-last-breadcrumb-link-interaction-voiceover_macos.collected.html)
- AT: VoiceOver for macOS (version 12.5.1)
- Browser: Safari (version 15.6.1)

## Review Conflicts for "Navigate to the last breadcrumb link"

1.  ### Unexpected Behaviors for "Ctrl+Option+Left, then Ctrl+Option+Left, then Ctrl+Option+Left" Command
    
    *   Tester IsaDC recorded output "end of Breadcrumb navigation You are currently in a navigation. end of list You are currently in a list. current page link Breadcrumb Example 4 of 4 You are currently on a link. To click this link, press Control-Option-Space. " and noted "Output is excessively verbose, e.g., includes redundant and/or irrelevant speech".
    *   Tester louis4533 recorded output "end of Breadcrumb navigation end of list current page link Breadcrumb Example 4 of 4" and noted no unexpected behavior.
    *   Tester jha11y recorded output "end of, Breadcrumb, navigation end of list current page, link, Breadcrumb Example, 4 of 4" and noted no unexpected behavior.
2.  ### Assertion Results for "Ctrl+Option+Left, then Ctrl+Option+Left, then Ctrl+Option+Left" Command and "Number of list items, 4, is conveyed" Assertion
    
    *   Tester IsaDC recorded output "end of Breadcrumb navigation You are currently in a navigation. end of list You are currently in a list. current page link Breadcrumb Example 4 of 4 You are currently on a link. To click this link, press Control-Option-Space. " and marked assertion as failing with no output.
    *   Tester louis4533 recorded output "end of Breadcrumb navigation end of list current page link Breadcrumb Example 4 of 4" and marked assertion as passing.
    *   Tester jha11y recorded output "end of, Breadcrumb, navigation end of list current page, link, Breadcrumb Example, 4 of 4" and marked assertion as passing.

**Comment by jscholes** [comment] 2022-11-14 19:32
@jha11y Thanks for raising this.  You wrote:

> The assertions seem to indicate that this is forward navigation as the don't mention boundaries. Other backward navigation tests have assertions that include boundary indication.

I think you're referring to the testing task titled "Navigate backwards out of the Breadcrumb navigation landmark", which does include the following assertions:

* Navigation landmark boundary is conveyed
* List boundary is conveyed

Similar assertions are included for the task "Navigate forwards out of the Breadcrumb navigation landmark".  In both cases, the user's starting position is inside the landmark/list, and they are navigationg out of it.

However, for the test linked in this issue, "Navigate to the last breadcrumb link", the user's starting point is outside the landmark, and the commands move them inside the landmark and list.  As such, the expected screen reader behaviour is different, e.g. we expect the number of list items to be spoken when entering a list, but not when moving out of it.

Please let me know if I've understood your report incorrectly, and/or if this doesn't address your concerns.  For now, I'll go ahead and close the issue, as the assertions are worded as intended.

**Closed by jscholes** 2022-11-14 19:32 UTC

**Comment by jha11y** [comment] 2022-11-16 13:27
Ok. if the assertions are correct then I'm good
