### ISSUE TITLE
change configuration instructions for VO to disable hints

### ISSUE THREAD

**Issue by robfentress** [w3c/aria-at#435] opened 2021-05-19 21:38 UTC
One issue I had when I was doing testing before was that I wasn't sure what to include when recording the output for VoiceOver.  In particular, in the default configuration, [VO announces hint text](https://www.apple.com/voiceover/info/guide/_1124.html#mchlp2701) about the item in the VO cursor after a brief delay.  I don't remember if we ever decided how to handle this.  Would it simplify things if we changed the [configuration instructions](https://github.com/w3c/aria-at/wiki/Configuring-Screen-Readers-for-Testing) to instruct testers to turn off hints in the VO Configuration Utlity before conducting testing?  Is any information we are looking for in our assertions communicated exclusively through hint text?  If hints are to remain enabled in our configuration recommendations, then I think we should probably add something to our instructions telling users to make sure to wait long enough for them to surface.

**Comment by jscholes** [comment] 2021-06-03 15:25
Closing this as a duplicate of #365.

**Closed by jscholes** 2021-06-03 15:25 UTC
Labels: Agenda+Community Group
