### ISSUE TITLE
Feedback: "Navigate backwards to a slider in reading mode" (Color Viewer Slider, Test 2)

### ISSUE THREAD

**Issue by jongund** [w3c/aria-at#893] opened 2023-02-16 15:18 UTC
## Description of Behavior

Shouldn't the there just be one up arrow, rather than 2 up arrows

## Test Setup

- Test File: [test-02-navigate-backwards-to-slider-reading-jaws.collected.html](https://aria-at.netlify.app/tests/horizontal-slider/test-02-navigate-backwards-to-slider-reading-jaws.collected.html)
- AT: JAWS (version 2022.2206.9)
- Browser: Chrome (version 110.0.0)

**Comment by jscholes** [comment] 2023-02-16 15:56
@jongund Thanks for the feedback.  The slider is labelled by a `div` before it.  To reach both the slider and label, two presses of Up Arrow are required, with the tester recording all output along the way.

I'll close this for now as the test is working as intended.  If you disagree or have additional questions, please do comment further.

**Closed by jscholes** 2023-02-16 15:56 UTC
