### ISSUE TITLE
Tester issue report for: "Navigate to menu item in menubar"

### ISSUE THREAD

**Issue by robfentress** [w3c/aria-at#252] opened 2020-06-01 22:02 UTC
### Test file at exact commit

[tests/menubar-editor/test-08-navigate-to-menuitem-in-menubar-interaction.html](https://github.com/w3c/aria-at/blob/2a3c46f1cbd20e7f2f0a706052d2d82aaf207a29/tests/menubar-editor/test-08-navigate-to-menuitem-in-menubar-interaction.html)

### Cycle:

Test Pilot (2020-05-27)

### AT:

VoiceOver for macOS (version macOs 10.15.4)

### Browser:

Chrome (version 83.0.4103.61)

### Description

When focus is set to the Font menu item automatically, VoiceOver begins reading the page starting from “Example region” and continuing on to the end of the page. This makes it unclear when the user is supposed to be running the commands. Should they execute the command immediately, just as VoiceOver is beginning to read the region role and name or after it has announced the Font menu item or what? I chose instead to pause reading immediately when the window was opened. Then I shift+tabbed to the previous focusable item. Then I tabbed back to the Font menu item. Then I executed the command.

**Comment by mcking65** [comment] 2020-06-02 04:57
closing as dupe of #258

**Closed by mcking65** 2020-06-02 04:57 UTC
Labels: duplicate
