### ISSUE TITLE
Coverage report page: broken link to collection of all current test plans

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at#675] opened 2022-04-02 23:41 UTC
The link to "collection of all current test plans" on the [coverage report page](https://github.com/w3c/aria-at/blob/master/metrics/coverage.md) is broken.

**Comment by jscholes** [comment] 2022-04-03 05:27
@s3ththompson I think this was caused by the work to switch to Netlify in https://github.com/w3c/aria-at/pull/621 and related PRs.  As PAC don't have access to the Netlify account to obtain a URL to a master deployment, I've re-assigned this issue to yourself for the time being.  Once that URL is available, please feel free to re-assign it back to me and I'm happy to update the metrics file.

As an aside, this may be a good opportunity to revisit the setup of infrastructure in this repo.  Right now, GitHub Pages is being used, but the build deployment will be on Netlify which is a separate system.

**Comment by jscholes** [comment] 2022-04-03 05:27
CC @richnoah

**Comment by howard-e** [comment] 2022-04-04 13:32
> ... I think this was caused by the work to switch to Netlify in #621 and related PRs.

That's right. #676 has been submitted to address this @jscholes @mcking65 

> As an aside, this may be a good opportunity to revisit the setup of infrastructure in this repo. Right now, GitHub Pages is being used, but the build deployment will be on Netlify which is a separate system.

Good note, we've gone ahead and disabled the GitHub Pages workflow

**Comment by howard-e** [comment] 2022-04-04 14:00
> GitHub pages is stull "on" for the repo https://w3c.github.io/aria-at/

Seems we have to remove the `gh-pages` branch to completely unpublish

**Closed** 2022-04-04 15:55 UTC
Labels: bug
