### ISSUE TITLE
include instructions to reset screen reader preferences?

### ISSUE THREAD

**Issue by robfentress** [w3c/aria-at#172] opened 2020-05-06 20:58 UTC
Should there be explicit instructions somewhere to [reset one's screen reader preferences](https://www.apple.com/voiceover/info/guide/_1136.html#vo27926) to their defaults before starting a test plan run?  Otherwise, I worry there may be inconsistent or difficult-to-interpret results because a Tester has their verbosity settings set a certain way or perhaps the last time they used VoiceOver they had [switched to Group Mode](https://www.apple.com/voiceover/info/guide/_1134.html#mchlp2711) and forgot to switch back to DOM Mode--things like that.

**Comment by zcorpan** [comment] 2020-05-12 14:55
Yes; this is a duplicate of https://github.com/w3c/aria-at/issues/113

**Closed by zcorpan** 2020-05-12 14:55 UTC
Labels: tests
